os: Visual Studio 2015

configuration: Release

before_build:
  - nuget restore
  
build:
  verbosity: minimal
  publish_wap: true

- vstest.console /logger:Appveyor "C:\projects\pipetest\x64\Release\TestPipe.dll"
