os: Visual Studio 2015

configuration: Debug

platform:
  - x86
  
build:
  verbosity: minimal
  publish_wap: true
test_script:
  - vstest.console /logger:Appveyor "C:\projects\pipetest\Release\TestPipe.dll"
